#!/usr/bin/env bash

set -e # stop on error

echo install gems...
bundle install
echo build jekyll...
JEKYLL_ENV=production bundle exec jekyll build
echo install npm modules...
npm install
echo run webpack build...
npm run build
echo chekout new master branch...
git checkout -b master
echo force add the built _site folder to branch...
git add -f _site
echo commit the changes...
git commit -m "deploy to production from source branch"
echo push to the remove master branch...
git push origin `git subtree split --prefix _site`:master --force
echo switch back to the source branch...
git checkout source
echo remove the temporary local master branch...
git branch -D master
